import type { Metadata } from "next";
import { Syne } from "next/font/google";
// import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import { ThemeProvider } from "next-themes";

const syne = Syne({ subsets: ["latin"] });
// const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quantum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${syne.className}`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
